### ISSUE TITLE
Not an issue. Letting you know I used it on an ad8400 and it works fine.

### ISSUE THREAD

**Issue by muttstang** [RobTillaart/AD520X#10]
I do have a couple of questions as I am trying to use it with a circuitpython project and there is no library for it. I looked through your library and I'm a newb with libraries. Is the baudrate 16000000?
Do you set the mode and the phase? 
What is the format of the data sent to the chip? 
I'm close to having it work but it's hit or miss if the chip reacts to the command or not

Thanks!!

**Comment by RobTillaart** [comment]
@muttstang 
Sorry for the extreme late reaction, this issues of this repo slipped through somehow
Thanks for testing the AD8400, I update the readme with this info

> Is the baudrate 16000000?

The max baudrate differs per board, e.g. the UNO can only do 4 Mbit.
Setting it to 16M gives most boards max performance.

> Do you set the mode and the phase?

These are set in **begin()**  
```  _spi_settings = SPISettings(_SPIspeed, MSBFIRST, SPI_MODE1);```

> What is the format of the data sent to the chip?

MSB_FIRST

Hope this answers your questions,
Again sorry for the late reply.

PS, I have worked on a dual channel command today in the develop branch. 
These wont work for the AD8400 of course as it has one channel.

**Comment by RobTillaart** [comment]
If questions are answered you may close the issue.

**Comment by muttstang** [comment]
No worries. I ended up running a different (i2c) chip and just using basic commands.
