### ISSUE TITLE
VSPI not declared in this scope

### ISSUE THREAD

**Issue by muttstang** [RobTillaart/AD520X#11]
I'm trying to use this code for an adafruit ESP32-S2 board using the 2.0.0 release of the arduino IDE and I get the following error:

`c:\Users\aerejb\Documents\Arduino\libraries\AD520X\AD520X.cpp: In member function 'void AD520X::begin(uint8_t)':
c:\Users\aerejb\Documents\Arduino\libraries\AD520X\AD520X.cpp:61:28: error: 'VSPI' was not declared in this scope
       mySPI = new SPIClass(VSPI);
                            ^~~~
c:\Users\aerejb\Documents\Arduino\libraries\AD520X\AD520X.cpp:61:28: note: suggested alternative: 'SPI'
       mySPI = new SPIClass(VSPI);
                            ^~~~
                            SPI

Compilation error: exit status 1`

My sketch is as follows: 
```cpp
#include "AD520X.h"

uint32_t start, stop;
// select, reset, shutdown, data, clock
AD8400 pot(10, 255, 255, 11, 13);  // SW SPI

// define inputs
const byte right_turn_input = A1;
const byte left_turn_input = 5;
const byte on_off_input = A3;
const byte speed_input = A2;

// define outputs
const byte right_turn_output = 2;
const byte left_turn_output = 4;
const byte on_off_output = 6;
const byte speed_output = 3;

// define variables

int speed_value = 0;
int satelite_count = 0;

bool motor_state = false;

float motor_offset_angle = 0;
float magnetic_declination = 0;
float boat_heading = 0;
float desired_heading = 0;

double actual_lattitude = 0;
double actual_longitude = 0;
double desired_lattitude = 0;
double desired_longitude = 0;





void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.println("Begin program");

  pot.begin(0); // set initial potentiometer value to zero (this gives you the wiper resistance 50-100 ohms)

  // define pin inputs
  pinMode(right_turn_input, INPUT);
  pinMode(left_turn_input, INPUT);
  pinMode(on_off_input, INPUT);
  pinMode(speed_input, INPUT);

  // define pin outputs
  pinMode(right_turn_output, OUTPUT);
  pinMode(left_turn_output, OUTPUT);
  pinMode(on_off_output, OUTPUT);
  pinMode(speed_output, OUTPUT);

}

void loop() {
  // put your main code here, to run repeatedly:
  delay(10);
  on_off();
  
  if (motor_state == true) {
    speed_calculation();
    steering_calculation();
  }
  //Serial.println(" ");
}

void speed_calculation() {
  // figure out what the speed value is
  
  speed_value = analogRead(speed_input) / 4;
  if (speed_value > 256) { speed_value = 256; }
  if (speed_value < 20) { speed_value = 0; }
  pot.setValue(0,speed_value);  // Set digital potentiometer value for the motor to read
  //analogWrite(speed_output, speed_value);
  Serial.print("Output speed value = "); Serial.print(speed_value); Serial.print(", ");
}

void steering_calculation() {
  // figure out what the steering should change
  if (digitalRead(right_turn_input) == 1) {
    digitalWrite(left_turn_output, 0);
    digitalWrite(right_turn_output, 1);
    Serial.print("Turn Right,  ");
  }
  delay(5);
  
  if (digitalRead(right_turn_input) == 0) {
    digitalWrite(right_turn_output, 0);
    Serial.print("deactivate right turn,  ");
  }
  delay(5);
  
  if (digitalRead(left_turn_input) == 1) {
    digitalWrite(right_turn_output, 0);
    digitalWrite(left_turn_output, 1);
    Serial.print("Turn Left,  ");
  }
  delay(5);
  
  if (digitalRead(left_turn_input) == 0) {
    digitalWrite(left_turn_output, 0);
    Serial.print("deactivate left turn,  ");
  }
  delay(5);
}

void on_off() {
  motor_state = digitalRead(on_off_input);
  digitalWrite(on_off_output, motor_state);
  
  if (motor_state == true) {
    Serial.println(", Motor on");
  }
  else {
    Serial.println(", Motor off");
  }
}
```

**Comment by muttstang** [comment]
This worked fine using some atmega based boards (uno and the sparkfun version as well) with a previous IDE release.  So I wonder if it's an issue with the ESP portion of the library

**Comment by RobTillaart** [comment]
@muttstang 
Sorry, this issue slipped also through.

Is the working on the ESP still a problem?

(updated the code in your post with syntax highlighting == 3 backquotes followed by cpp  )

> 2.0.0 release of the arduino IDE

This one is only released recently, so that would be a BETA version.  I have not worked with that one yet.

> adafruit ESP32-S2 board  .... 'VSPI' was not declared in this scope

if you look at https://learn.adafruit.com/assets/110677 you will see it does not have a VSPI indeed.
There are (too) many different ESP32 variations to test and verify them all unfortunately.
I expect it to work with the HSPI interface as IIRC that is default.

If this answers your question, you can close the issue.

Sorry again for the late reply.

**Comment by RobTillaart** [comment]
Think that easiest way is to remove/comment the VSPI related lines from the library.

If you know of a check to see if VSPI is supported, please let me know as this problem exists in all my SPI based libraries.
Would allow me to fix them all in time.

**Comment by RobTillaart** [comment]
@muttstang 
Don't know if this will work, do not have hardware to test.
If you have time to test, would be appreciated.

AD520X.cpp - line 60++

```cpp
#ifdef VSPI
      mySPI = new SPIClass(VSPI);
      mySPI->end();
      mySPI->begin(18, 19, 23, _select);   //  CLK=18 MISO=19 MOSI=23
#endif
```

**Comment by RobTillaart** [comment]
Did some investigation in the ESP32 package and found defines in this file **esp32-hal-spi.h**

```cpp
#define FSPI  1 //SPI bus attached to the flash (can use the same data lines but different SS)
#define HSPI  2 //SPI bus normally mapped to pins 12 - 15, but can be matrixed to any pins
#define VSPI  3 //SPI bus normally attached to pins 5, 18, 19 and 23, but can be matrixed to any pins
```

So it seems that the above conditional compilation trick should work.
