### ISSUE TITLE
Inverted Logic on AD8403

### ISSUE THREAD

**Issue by Ale11Re** [RobTillaart/AD520X#13]
Hi,
I was playing around with the AD8403 chip and I noticed that Shutdown and Reset logic are inverted.
They're both active LOW. In fact, if shutdown is LOW, the output is disabled. Looking deep into the library source it's exactly the opposite. Cannot understand how it works with AD5204 as it shares the same logic principle.

**Comment by RobTillaart** [comment]
Solved with PR #15
