### ISSUE TITLE
Wrong SPI_MODE for AD8403

### ISSUE THREAD

**Issue by Ale11Re** [RobTillaart/AD520X#14]
Hi,
I noticed that using pot.setValue(0, x) and pot.setValue(1, x) has effect on potentiometer 1 both in half scale.
Similarly, using pot.setValue(2, x) and pot.setValue(3, x) has effect on potentiometer 2.
Could not find effect on potentiometer 3 and 4.

**Comment by Ale11Re** [comment]
By playing around I solved the issue by changing SPI_MODE. AD8403 will work with all SPI Modes BUT SPI_MODE1 which is default with the library.
I still need to investigate which SPI mode is optimal for this chip. Meanwhile it's working now...

**Comment by RobTillaart** [comment]
Solved with PR #15
