### ISSUE TITLE
Verify 0.3.0 with AD5206 hardware

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/AD520X#17]
- order hardware (done)
- test AVR 
- test ESP32

**Comment by RobTillaart** [comment]
@Ale11Re 

Release 0.3.0 is in the making.

**Comment by Ale11Re** [comment]
@RobTillaart 
That's fantastic! Great job!
By curiosity, did you manage to test with AD5206 you ordered a while ago? Is it working fine?
Sorry for replying late but I've been busy.

**Comment by RobTillaart** [comment]
Yes, I have tested on UNO and ESP32 and do not recall problems (3weeks ago is an "eternity") Would have mentioned them here.
